name: Quality code

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Setup bunjs
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun install --frozen-lockfile

      - name: Run Pint
        run: composer pint:ci

      - name: Run PHPStan
        run: composer types

      - name: Format Frontend
        run: bun run fmt:ci

      - name: Lint Frontend
        run: bun run lint:ci
